DROP PROCEDURE IF EXISTS populate_audit;
DELIMITER $$
CREATE PROCEDURE populate_audit()
BEGIN
  DECLARE i INT DEFAULT 0;
  SET FOREIGN_KEY_CHECKS=0; TRUNCATE Audit; SET FOREIGN_KEY_CHECKS=1;

  WHILE i < 1000000 DO
    INSERT INTO Audit(Game_ID, Audited_On, Copies_Stocked) 
    VALUES (i+1, FROM_UNIXTIME(UNIX_TIMESTAMP('2014-01-01 01:00:00')+FLOOR(RAND()*31536000)), FLOOR(ROUND(RAND()*100,2)));
    
    SET i = i + 1;
  END WHILE;
END$$
DELIMITER ;
